# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Natsuky - Kawaii Fashion
email: hello@natsuky.com
description: > # this means to ignore newlines until "baseurl:"
  We create collections of awesome kawaii products that you will love to have.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.natsuky.com" # the base hostname & protocol for your site
twitter_username: NatsukyFashion
permalink: none

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed

gems: [jekyll-paginate, jekyll-paginate-category]

paginate: 5
paginate_path: "page:num"

category_dir: "category"
category_layout: "index.html"